## Azure Devops Agent Variables to set
## ref:  https://docs.microsoft.com/es-es/azure/devops/pipelines/agents/docker?view=azure-devops#linux
##
azp:
  url: "https://dev.azure.com/yourazuregroup"
  token: "myverysecuretoken"
  agent_name: "mydockeragent"
  pool: "Default"
  work: "_work"

## Environment Secret Names
## If defined, this chart sets secrets as environment vars
## For instance, creating a secret like that:
## kubectl create secret generic appsecrets --from-literal=username='my-app'
## and adding "appsecrets" to this var
secrets: []
#- name: k8s-access

## Azure Devops Agent Documentation
## ref:  https://docs.microsoft.com/es-es/azure/devops/pipelines/agents/docker?view=azure-devops#linux
##
image:
  ## Azure Devops image version
  ## ref: https://hub.docker.com/repository/docker/jmferrer/azure-devops-agent
  registry: docker.io
  repository: jmferrer/azure-devops-agent
  tag: latest
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## String to partially override azure-devops-agent.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override azure-devops-agent.fullname template
##
# fullnameOverride:

## Number of agents in statefulset
##
replicaCount: 1


## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 300m

## HTTP proxy endpoint to use for containers.
##
http_proxy:

## HTTPS proxy endpoint to use for containers.
##
https_proxy:

## Blacklist of addresses to skip the proxy when reaching.
##
no_proxy:

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

sidecars:
## Add sidecars to the pod.
## e.g.
# - name: your-image-name
  # image: your-image
  # imagePullPolicy: Always
  # ports:
  # - name: portname
  #   containerPort: 1234
