{{ if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-devops-agent.fullname" . }}
  labels:
    app: "{{ template "azure-devops-agent.name" . }}"
    chart: "{{ template "azure-devops-agent.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  azp_url: "{{ .Values.azp.url | b64enc }}"
  azp_token: "{{ .Values.azp.token | b64enc }}"
  azp_agent_name: "{{ .Values.azp.agent_name | b64enc }}"
  azp_pool: "{{ .Values.azp.pool | b64enc }}"
  azp_work: "{{ .Values.azp.work | b64enc }}"
{{ end }}